# Makefile

# Compiler

CXX = g++

# Compiler flags

CXXFLAGS = -std=c++11 -Wall -Wextra

# Executable name

TARGET = unitTesting

# Source files

SRCS = testMain.cpp menu.h game.h airMonster.cpp earthMonster.cpp fireMonster.cpp waterMonster.cpp elementalDragon.cpp  monster.h  AirPlayer.cpp EarthPlayer.cpp FirePlayer.cpp WaterPlayer.cpp Spell.cpp Player.cpp unitTest.h FireJourney.h WaterJourney.h EarthJourney.h AirJourney.h

# Build and run tests

.PHONY: all

all:

	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRCS)

	./$(TARGET)

# Clean rule

.PHONY: clean

clean:

	rm -f $(TARGET)


